language: node_js
node_js:
- 5.0.0
deploy:
  provider: heroku
  api_key:
    secure: tGx07XuL1DWTPKpqFJaxYEGBAt1cmlXJ7LD78D53NSTEIZH5In/hrtzMaTt3o9c1A3zpJvONVPgOxpKbgx9bOe7d1YWyKn2Frt1f7JhNCbqLm3AAVWrLKi1gP8FrVa9F6UbaBKG2wknp8rLzM2dLsIiqeZPdtKxlnIGHotixXf8E80/qgxb+lv1NpuC7Ipu5rVMmi1o6UnXI+APOH//QxAG6ynXG73f29sf0OBK4LkS9SQ0JS15lhm14y/hPwIeIEZYrw3kx81r6plqTlQN646K/K8DrcrE0HHLnx+W5h2VyDRt6RhheQyzxJ80pF8tbDBOA5Vkpjj+5qpZtGVvzNoLR0jLPzkRRl5ucVHVZBxqDLaBLMgSOg9Ech+yH1sNVyuMR5ZDuOdV6CHH7XTpB748LYZxo+RX81eQlSWnfpZpAayRMVBRm0MxzsXgSTJyzjOj/YJTfnAbrUz2qhvKGOnIry3T994zeWMX/mokZ5uujWH0K0aaTZLf/i+51uwEezkj+bTTUxdPamJaDsA40JevZtIxb4R3ik7gYMS6qE5dIw9OAGo5wzwGOx6JQP6vQwbQrFtdkUUSoC0Kgp+5SpxPtA7UApleVh8AL04z+pRjLIHCboknmrxq7G6cAnU/gYoJXXZXGv9T8uSOucOM+EzjKK0XXgCvnmR5WHbIJeaE=
  app: kogis-tatry
env:
- MAILGUN_API=key-46cebd38c59ac222e6fbcf1581411eaf
- MAILGUN_DOMAIN=sandboxf0212096472d43109ac45a55542348ec.mailgun.org
- MAILGUN_RECEIVER=tomek.rybka@gmail.com
